/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateIdentifierResponse model module.
 * @module model/CreateIdentifierResponse
 * @version 1.0.0
 */
class CreateIdentifierResponse {
    /**
     * Constructs a new <code>CreateIdentifierResponse</code>.
     * Response when creating an identifier
     * @alias module:model/CreateIdentifierResponse
     */
    constructor() { 
        
        CreateIdentifierResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateIdentifierResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateIdentifierResponse} obj Optional instance to populate.
     * @return {module:model/CreateIdentifierResponse} The populated <code>CreateIdentifierResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateIdentifierResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Number');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateIdentifierResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateIdentifierResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }

        return true;
    }


}



/**
 * Whether the operation succeeded
 * @member {Number} success
 */
CreateIdentifierResponse.prototype['success'] = undefined;

/**
 * The newly created identifier UUID
 * @member {String} identifier
 */
CreateIdentifierResponse.prototype['identifier'] = undefined;






export default CreateIdentifierResponse;

