/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FtcIdentifyUrlResponse model module.
 * @module model/FtcIdentifyUrlResponse
 * @version 1.0.0
 */
class FtcIdentifyUrlResponse {
    /**
     * Constructs a new <code>FtcIdentifyUrlResponse</code>.
     * Response containing the FTC or Identify URL and QR code
     * @alias module:model/FtcIdentifyUrlResponse
     */
    constructor() { 
        
        FtcIdentifyUrlResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FtcIdentifyUrlResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FtcIdentifyUrlResponse} obj Optional instance to populate.
     * @return {module:model/FtcIdentifyUrlResponse} The populated <code>FtcIdentifyUrlResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FtcIdentifyUrlResponse();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('qr')) {
                obj['qr'] = ApiClient.convertToType(data['qr'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FtcIdentifyUrlResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FtcIdentifyUrlResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['qr'] && !(typeof data['qr'] === 'string' || data['qr'] instanceof String)) {
            throw new Error("Expected the field `qr` to be a primitive type in the JSON string but got " + data['qr']);
        }

        return true;
    }


}



/**
 * The one-time URL for FTC or identification
 * @member {String} url
 */
FtcIdentifyUrlResponse.prototype['url'] = undefined;

/**
 * QR code representation of the URL
 * @member {String} qr
 */
FtcIdentifyUrlResponse.prototype['qr'] = undefined;






export default FtcIdentifyUrlResponse;

