/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FtcSetupRequestBody model module.
 * @module model/FtcSetupRequestBody
 * @version 1.0.0
 */
class FtcSetupRequestBody {
    /**
     * Constructs a new <code>FtcSetupRequestBody</code>.
     * Request body for First Time Connection setup
     * @alias module:model/FtcSetupRequestBody
     * @param connectionNid {String} The connection NID
     * @param connectionTokenHash {String} The hashed connection token
     * @param returnTo {String} The URL to return to after connection
     */
    constructor(connectionNid, connectionTokenHash, returnTo) { 
        
        FtcSetupRequestBody.initialize(this, connectionNid, connectionTokenHash, returnTo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, connectionNid, connectionTokenHash, returnTo) { 
        obj['connection_nid'] = connectionNid;
        obj['connection_token_hash'] = connectionTokenHash;
        obj['return_to'] = returnTo;
    }

    /**
     * Constructs a <code>FtcSetupRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FtcSetupRequestBody} obj Optional instance to populate.
     * @return {module:model/FtcSetupRequestBody} The populated <code>FtcSetupRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FtcSetupRequestBody();

            if (data.hasOwnProperty('connection_nid')) {
                obj['connection_nid'] = ApiClient.convertToType(data['connection_nid'], 'String');
            }
            if (data.hasOwnProperty('connection_token_hash')) {
                obj['connection_token_hash'] = ApiClient.convertToType(data['connection_token_hash'], 'String');
            }
            if (data.hasOwnProperty('return_to')) {
                obj['return_to'] = ApiClient.convertToType(data['return_to'], 'String');
            }
            if (data.hasOwnProperty('mydexid')) {
                obj['mydexid'] = ApiClient.convertToType(data['mydexid'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('linking_token')) {
                obj['linking_token'] = ApiClient.convertToType(data['linking_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FtcSetupRequestBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FtcSetupRequestBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FtcSetupRequestBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['connection_nid'] && !(typeof data['connection_nid'] === 'string' || data['connection_nid'] instanceof String)) {
            throw new Error("Expected the field `connection_nid` to be a primitive type in the JSON string but got " + data['connection_nid']);
        }
        // ensure the json data is a string
        if (data['connection_token_hash'] && !(typeof data['connection_token_hash'] === 'string' || data['connection_token_hash'] instanceof String)) {
            throw new Error("Expected the field `connection_token_hash` to be a primitive type in the JSON string but got " + data['connection_token_hash']);
        }
        // ensure the json data is a string
        if (data['return_to'] && !(typeof data['return_to'] === 'string' || data['return_to'] instanceof String)) {
            throw new Error("Expected the field `return_to` to be a primitive type in the JSON string but got " + data['return_to']);
        }
        // ensure the json data is a string
        if (data['mydexid'] && !(typeof data['mydexid'] === 'string' || data['mydexid'] instanceof String)) {
            throw new Error("Expected the field `mydexid` to be a primitive type in the JSON string but got " + data['mydexid']);
        }
        // ensure the json data is a string
        if (data['linking_token'] && !(typeof data['linking_token'] === 'string' || data['linking_token'] instanceof String)) {
            throw new Error("Expected the field `linking_token` to be a primitive type in the JSON string but got " + data['linking_token']);
        }

        return true;
    }


}

FtcSetupRequestBody.RequiredProperties = ["connection_nid", "connection_token_hash", "return_to"];

/**
 * The connection NID
 * @member {String} connection_nid
 */
FtcSetupRequestBody.prototype['connection_nid'] = undefined;

/**
 * The hashed connection token
 * @member {String} connection_token_hash
 */
FtcSetupRequestBody.prototype['connection_token_hash'] = undefined;

/**
 * The URL to return to after connection
 * @member {String} return_to
 */
FtcSetupRequestBody.prototype['return_to'] = undefined;

/**
 * The MydexID if already known (required if version > 1)
 * @member {String} mydexid
 */
FtcSetupRequestBody.prototype['mydexid'] = undefined;

/**
 * The connection version (default 1, must be >= 1)
 * @member {Number} version
 */
FtcSetupRequestBody.prototype['version'] = undefined;

/**
 * A unique ID representing the member in the subscriber's backend
 * @member {String} linking_token
 */
FtcSetupRequestBody.prototype['linking_token'] = undefined;






export default FtcSetupRequestBody;

