/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdentifierObject from './IdentifierObject';

/**
 * The GetIdentifiersResponse model module.
 * @module model/GetIdentifiersResponse
 * @version 1.0.0
 */
class GetIdentifiersResponse {
    /**
     * Constructs a new <code>GetIdentifiersResponse</code>.
     * Response when getting all identifiers for a member
     * @alias module:model/GetIdentifiersResponse
     */
    constructor() { 
        
        GetIdentifiersResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetIdentifiersResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetIdentifiersResponse} obj Optional instance to populate.
     * @return {module:model/GetIdentifiersResponse} The populated <code>GetIdentifiersResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetIdentifiersResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Number');
            }
            if (data.hasOwnProperty('identifiers')) {
                obj['identifiers'] = ApiClient.convertToType(data['identifiers'], [IdentifierObject]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetIdentifiersResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetIdentifiersResponse</code>.
     */
    static validateJSON(data) {
        if (data['identifiers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['identifiers'])) {
                throw new Error("Expected the field `identifiers` to be an array in the JSON data but got " + data['identifiers']);
            }
            // validate the optional field `identifiers` (array)
            for (const item of data['identifiers']) {
                IdentifierObject.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} success
 */
GetIdentifiersResponse.prototype['success'] = undefined;

/**
 * @member {Array.<module:model/IdentifierObject>} identifiers
 */
GetIdentifiersResponse.prototype['identifiers'] = undefined;






export default GetIdentifiersResponse;

