/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentifierAuthObject model module.
 * @module model/IdentifierAuthObject
 * @version 1.0.0
 */
class IdentifierAuthObject {
    /**
     * Constructs a new <code>IdentifierAuthObject</code>.
     * Authentication data for an identifier
     * @alias module:model/IdentifierAuthObject
     */
    constructor() { 
        
        IdentifierAuthObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdentifierAuthObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentifierAuthObject} obj Optional instance to populate.
     * @return {module:model/IdentifierAuthObject} The populated <code>IdentifierAuthObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentifierAuthObject();

            if (data.hasOwnProperty('parent_uuid')) {
                obj['parent_uuid'] = ApiClient.convertToType(data['parent_uuid'], 'String');
            }
            if (data.hasOwnProperty('app_url')) {
                obj['app_url'] = ApiClient.convertToType(data['app_url'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('con_nid')) {
                obj['con_nid'] = ApiClient.convertToType(data['con_nid'], 'String');
            }
            if (data.hasOwnProperty('org_id')) {
                obj['org_id'] = ApiClient.convertToType(data['org_id'], 'String');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'String');
            }
            if (data.hasOwnProperty('item_id')) {
                obj['item_id'] = ApiClient.convertToType(data['item_id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdentifierAuthObject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdentifierAuthObject</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['parent_uuid'] && !(typeof data['parent_uuid'] === 'string' || data['parent_uuid'] instanceof String)) {
            throw new Error("Expected the field `parent_uuid` to be a primitive type in the JSON string but got " + data['parent_uuid']);
        }
        // ensure the json data is a string
        if (data['app_url'] && !(typeof data['app_url'] === 'string' || data['app_url'] instanceof String)) {
            throw new Error("Expected the field `app_url` to be a primitive type in the JSON string but got " + data['app_url']);
        }
        // ensure the json data is a string
        if (data['client_id'] && !(typeof data['client_id'] === 'string' || data['client_id'] instanceof String)) {
            throw new Error("Expected the field `client_id` to be a primitive type in the JSON string but got " + data['client_id']);
        }
        // ensure the json data is a string
        if (data['con_nid'] && !(typeof data['con_nid'] === 'string' || data['con_nid'] instanceof String)) {
            throw new Error("Expected the field `con_nid` to be a primitive type in the JSON string but got " + data['con_nid']);
        }
        // ensure the json data is a string
        if (data['org_id'] && !(typeof data['org_id'] === 'string' || data['org_id'] instanceof String)) {
            throw new Error("Expected the field `org_id` to be a primitive type in the JSON string but got " + data['org_id']);
        }
        // ensure the json data is a string
        if (data['project_id'] && !(typeof data['project_id'] === 'string' || data['project_id'] instanceof String)) {
            throw new Error("Expected the field `project_id` to be a primitive type in the JSON string but got " + data['project_id']);
        }
        // ensure the json data is a string
        if (data['item_id'] && !(typeof data['item_id'] === 'string' || data['item_id'] instanceof String)) {
            throw new Error("Expected the field `item_id` to be a primitive type in the JSON string but got " + data['item_id']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * The parent identifier UUID
 * @member {String} parent_uuid
 */
IdentifierAuthObject.prototype['parent_uuid'] = undefined;

/**
 * The application URL
 * @member {String} app_url
 */
IdentifierAuthObject.prototype['app_url'] = undefined;

/**
 * The OAuth2 client ID
 * @member {String} client_id
 */
IdentifierAuthObject.prototype['client_id'] = undefined;

/**
 * The connection NID
 * @member {String} con_nid
 */
IdentifierAuthObject.prototype['con_nid'] = undefined;

/**
 * The organization ID
 * @member {String} org_id
 */
IdentifierAuthObject.prototype['org_id'] = undefined;

/**
 * The project ID
 * @member {String} project_id
 */
IdentifierAuthObject.prototype['project_id'] = undefined;

/**
 * The item ID
 * @member {String} item_id
 */
IdentifierAuthObject.prototype['item_id'] = undefined;

/**
 * The type of identifier/auth
 * @member {String} type
 */
IdentifierAuthObject.prototype['type'] = undefined;






export default IdentifierAuthObject;

