/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentifierObject model module.
 * @module model/IdentifierObject
 * @version 1.0.0
 */
class IdentifierObject {
    /**
     * Constructs a new <code>IdentifierObject</code>.
     * An identifier record
     * @alias module:model/IdentifierObject
     */
    constructor() { 
        
        IdentifierObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdentifierObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentifierObject} obj Optional instance to populate.
     * @return {module:model/IdentifierObject} The populated <code>IdentifierObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentifierObject();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('parent_uuid')) {
                obj['parent_uuid'] = ApiClient.convertToType(data['parent_uuid'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IdentifierObject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IdentifierObject</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['parent_uuid'] && !(typeof data['parent_uuid'] === 'string' || data['parent_uuid'] instanceof String)) {
            throw new Error("Expected the field `parent_uuid` to be a primitive type in the JSON string but got " + data['parent_uuid']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['created'] && !(typeof data['created'] === 'string' || data['created'] instanceof String)) {
            throw new Error("Expected the field `created` to be a primitive type in the JSON string but got " + data['created']);
        }

        return true;
    }


}



/**
 * Database ID of the identifier
 * @member {String} id
 */
IdentifierObject.prototype['id'] = undefined;

/**
 * The UUID identifier
 * @member {String} identifier
 */
IdentifierObject.prototype['identifier'] = undefined;

/**
 * The parent identifier UUID if this is a child
 * @member {String} parent_uuid
 */
IdentifierObject.prototype['parent_uuid'] = undefined;

/**
 * The type of identifier
 * @member {String} type
 */
IdentifierObject.prototype['type'] = undefined;

/**
 * Creation timestamp
 * @member {String} created
 */
IdentifierObject.prototype['created'] = undefined;






export default IdentifierObject;

