/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InviteRequestBody model module.
 * @module model/InviteRequestBody
 * @version 1.0.0
 */
class InviteRequestBody {
    /**
     * Constructs a new <code>InviteRequestBody</code>.
     * Request body for storing and sending an identifier invite
     * @alias module:model/InviteRequestBody
     * @param identifier {String} The parent identifier
     * @param appUrl {String} The application URL
     * @param clientId {String} The OAuth2 client ID
     * @param conNid {String} The connection NID
     * @param orgId {String} The organization ID
     * @param projectId {String} The project ID
     * @param itemId {String} The item ID
     * @param type {String} The type of invitation
     * @param messageEmail {String} Email message content
     */
    constructor(identifier, appUrl, clientId, conNid, orgId, projectId, itemId, type, messageEmail) { 
        
        InviteRequestBody.initialize(this, identifier, appUrl, clientId, conNid, orgId, projectId, itemId, type, messageEmail);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier, appUrl, clientId, conNid, orgId, projectId, itemId, type, messageEmail) { 
        obj['identifier'] = identifier;
        obj['app_url'] = appUrl;
        obj['client_id'] = clientId;
        obj['con_nid'] = conNid;
        obj['org_id'] = orgId;
        obj['project_id'] = projectId;
        obj['item_id'] = itemId;
        obj['type'] = type;
        obj['message_email'] = messageEmail;
    }

    /**
     * Constructs a <code>InviteRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InviteRequestBody} obj Optional instance to populate.
     * @return {module:model/InviteRequestBody} The populated <code>InviteRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteRequestBody();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('app_url')) {
                obj['app_url'] = ApiClient.convertToType(data['app_url'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('con_nid')) {
                obj['con_nid'] = ApiClient.convertToType(data['con_nid'], 'String');
            }
            if (data.hasOwnProperty('org_id')) {
                obj['org_id'] = ApiClient.convertToType(data['org_id'], 'String');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'String');
            }
            if (data.hasOwnProperty('item_id')) {
                obj['item_id'] = ApiClient.convertToType(data['item_id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('message_email')) {
                obj['message_email'] = ApiClient.convertToType(data['message_email'], 'String');
            }
            if (data.hasOwnProperty('message_sms')) {
                obj['message_sms'] = ApiClient.convertToType(data['message_sms'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InviteRequestBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InviteRequestBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InviteRequestBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }
        // ensure the json data is a string
        if (data['app_url'] && !(typeof data['app_url'] === 'string' || data['app_url'] instanceof String)) {
            throw new Error("Expected the field `app_url` to be a primitive type in the JSON string but got " + data['app_url']);
        }
        // ensure the json data is a string
        if (data['client_id'] && !(typeof data['client_id'] === 'string' || data['client_id'] instanceof String)) {
            throw new Error("Expected the field `client_id` to be a primitive type in the JSON string but got " + data['client_id']);
        }
        // ensure the json data is a string
        if (data['con_nid'] && !(typeof data['con_nid'] === 'string' || data['con_nid'] instanceof String)) {
            throw new Error("Expected the field `con_nid` to be a primitive type in the JSON string but got " + data['con_nid']);
        }
        // ensure the json data is a string
        if (data['org_id'] && !(typeof data['org_id'] === 'string' || data['org_id'] instanceof String)) {
            throw new Error("Expected the field `org_id` to be a primitive type in the JSON string but got " + data['org_id']);
        }
        // ensure the json data is a string
        if (data['project_id'] && !(typeof data['project_id'] === 'string' || data['project_id'] instanceof String)) {
            throw new Error("Expected the field `project_id` to be a primitive type in the JSON string but got " + data['project_id']);
        }
        // ensure the json data is a string
        if (data['item_id'] && !(typeof data['item_id'] === 'string' || data['item_id'] instanceof String)) {
            throw new Error("Expected the field `item_id` to be a primitive type in the JSON string but got " + data['item_id']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['message_email'] && !(typeof data['message_email'] === 'string' || data['message_email'] instanceof String)) {
            throw new Error("Expected the field `message_email` to be a primitive type in the JSON string but got " + data['message_email']);
        }
        // ensure the json data is a string
        if (data['message_sms'] && !(typeof data['message_sms'] === 'string' || data['message_sms'] instanceof String)) {
            throw new Error("Expected the field `message_sms` to be a primitive type in the JSON string but got " + data['message_sms']);
        }

        return true;
    }


}

InviteRequestBody.RequiredProperties = ["identifier", "app_url", "client_id", "con_nid", "org_id", "project_id", "item_id", "type", "message_email"];

/**
 * The parent identifier
 * @member {String} identifier
 */
InviteRequestBody.prototype['identifier'] = undefined;

/**
 * The application URL
 * @member {String} app_url
 */
InviteRequestBody.prototype['app_url'] = undefined;

/**
 * The OAuth2 client ID
 * @member {String} client_id
 */
InviteRequestBody.prototype['client_id'] = undefined;

/**
 * The connection NID
 * @member {String} con_nid
 */
InviteRequestBody.prototype['con_nid'] = undefined;

/**
 * The organization ID
 * @member {String} org_id
 */
InviteRequestBody.prototype['org_id'] = undefined;

/**
 * The project ID
 * @member {String} project_id
 */
InviteRequestBody.prototype['project_id'] = undefined;

/**
 * The item ID
 * @member {String} item_id
 */
InviteRequestBody.prototype['item_id'] = undefined;

/**
 * The type of invitation
 * @member {String} type
 */
InviteRequestBody.prototype['type'] = undefined;

/**
 * Email message content
 * @member {String} message_email
 */
InviteRequestBody.prototype['message_email'] = undefined;

/**
 * SMS message content
 * @member {String} message_sms
 */
InviteRequestBody.prototype['message_sms'] = undefined;






export default InviteRequestBody;

