/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdentifierAuthObject from './IdentifierAuthObject';

/**
 * The NotifyMemberRequestBody model module.
 * @module model/NotifyMemberRequestBody
 * @version 1.0.0
 */
class NotifyMemberRequestBody {
    /**
     * Constructs a new <code>NotifyMemberRequestBody</code>.
     * Request body for sending a notification to a member
     * @alias module:model/NotifyMemberRequestBody
     * @param identifierAuth {module:model/IdentifierAuthObject} 
     * @param messageEmail {String} Email message content
     */
    constructor(identifierAuth, messageEmail) { 
        
        NotifyMemberRequestBody.initialize(this, identifierAuth, messageEmail);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifierAuth, messageEmail) { 
        obj['identifier_auth'] = identifierAuth;
        obj['message_email'] = messageEmail;
    }

    /**
     * Constructs a <code>NotifyMemberRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NotifyMemberRequestBody} obj Optional instance to populate.
     * @return {module:model/NotifyMemberRequestBody} The populated <code>NotifyMemberRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotifyMemberRequestBody();

            if (data.hasOwnProperty('identifier_auth')) {
                obj['identifier_auth'] = IdentifierAuthObject.constructFromObject(data['identifier_auth']);
            }
            if (data.hasOwnProperty('message_email')) {
                obj['message_email'] = ApiClient.convertToType(data['message_email'], 'String');
            }
            if (data.hasOwnProperty('message_sms')) {
                obj['message_sms'] = ApiClient.convertToType(data['message_sms'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NotifyMemberRequestBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NotifyMemberRequestBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NotifyMemberRequestBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `identifier_auth`
        if (data['identifier_auth']) { // data not null
          IdentifierAuthObject.validateJSON(data['identifier_auth']);
        }
        // ensure the json data is a string
        if (data['message_email'] && !(typeof data['message_email'] === 'string' || data['message_email'] instanceof String)) {
            throw new Error("Expected the field `message_email` to be a primitive type in the JSON string but got " + data['message_email']);
        }
        // ensure the json data is a string
        if (data['message_sms'] && !(typeof data['message_sms'] === 'string' || data['message_sms'] instanceof String)) {
            throw new Error("Expected the field `message_sms` to be a primitive type in the JSON string but got " + data['message_sms']);
        }

        return true;
    }


}

NotifyMemberRequestBody.RequiredProperties = ["identifier_auth", "message_email"];

/**
 * @member {module:model/IdentifierAuthObject} identifier_auth
 */
NotifyMemberRequestBody.prototype['identifier_auth'] = undefined;

/**
 * Email message content
 * @member {String} message_email
 */
NotifyMemberRequestBody.prototype['message_email'] = undefined;

/**
 * SMS message content
 * @member {String} message_sms
 */
NotifyMemberRequestBody.prototype['message_sms'] = undefined;






export default NotifyMemberRequestBody;

