/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateNotificationStatusRequestBody model module.
 * @module model/UpdateNotificationStatusRequestBody
 * @version 1.0.0
 */
class UpdateNotificationStatusRequestBody {
    /**
     * Constructs a new <code>UpdateNotificationStatusRequestBody</code>.
     * Request body for updating notification status
     * @alias module:model/UpdateNotificationStatusRequestBody
     * @param identifier {String} The notification identifier to update
     */
    constructor(identifier) { 
        
        UpdateNotificationStatusRequestBody.initialize(this, identifier);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier) { 
        obj['identifier'] = identifier;
    }

    /**
     * Constructs a <code>UpdateNotificationStatusRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateNotificationStatusRequestBody} obj Optional instance to populate.
     * @return {module:model/UpdateNotificationStatusRequestBody} The populated <code>UpdateNotificationStatusRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateNotificationStatusRequestBody();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateNotificationStatusRequestBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateNotificationStatusRequestBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateNotificationStatusRequestBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['identifier'] && !(typeof data['identifier'] === 'string' || data['identifier'] instanceof String)) {
            throw new Error("Expected the field `identifier` to be a primitive type in the JSON string but got " + data['identifier']);
        }

        return true;
    }


}

UpdateNotificationStatusRequestBody.RequiredProperties = ["identifier"];

/**
 * The notification identifier to update
 * @member {String} identifier
 */
UpdateNotificationStatusRequestBody.prototype['identifier'] = undefined;






export default UpdateNotificationStatusRequestBody;

