/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthErrorResponse from '../model/AuthErrorResponse';
import ErrorResponse from '../model/ErrorResponse';
import FtcSetupRequestBody from '../model/FtcSetupRequestBody';
import FtcUrlResponse from '../model/FtcUrlResponse';
import IdentifyRequestBody from '../model/IdentifyRequestBody';
import IdentifyUrlResponse from '../model/IdentifyUrlResponse';

/**
* Connections service.
* @module api/ConnectionsApi
* @version 1.0.0
*/
export default class ConnectionsApi {

    /**
    * Constructs a new ConnectionsApi. 
    * @alias module:api/ConnectionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the postFtcSetup operation.
     * @callback module:api/ConnectionsApi~postFtcSetupCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FtcUrlResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set up a First Time Connection URL.
     * Generates a one-time URL for a member to complete First Time Connection. Requires OAuth2.0 authentication.
     * @param {Object} opts Optional parameters
     * @param {module:model/FtcSetupRequestBody} [ftcSetupRequestBody] 
     * @param {module:api/ConnectionsApi~postFtcSetupCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FtcUrlResponse}
     */
    postFtcSetup(opts, callback) {
      opts = opts || {};
      let postBody = opts['ftcSetupRequestBody'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = FtcUrlResponse;
      return this.apiClient.callApi(
        '/ftc/setup', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postIdentify operation.
     * @callback module:api/ConnectionsApi~postIdentifyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IdentifyUrlResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set up an identification URL.
     * Generates a one-time URL for identifying a member without requiring them to know their MydexID. Requires OAuth2.0 authentication.
     * @param {Object} opts Optional parameters
     * @param {module:model/IdentifyRequestBody} [identifyRequestBody] 
     * @param {module:api/ConnectionsApi~postIdentifyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IdentifyUrlResponse}
     */
    postIdentify(opts, callback) {
      opts = opts || {};
      let postBody = opts['identifyRequestBody'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = IdentifyUrlResponse;
      return this.apiClient.callApi(
        '/identify', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
