/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthErrorResponse from '../model/AuthErrorResponse';
import CreateIdentifierResponse from '../model/CreateIdentifierResponse';
import ErrorResponse from '../model/ErrorResponse';
import GetInviteResponse from '../model/GetInviteResponse';
import InviteRequestBody from '../model/InviteRequestBody';
import InviteStatusRequestBody from '../model/InviteStatusRequestBody';
import InviteStatusResponse from '../model/InviteStatusResponse';
import NotifyMemberRequestBody from '../model/NotifyMemberRequestBody';
import UpdateNotificationStatusRequestBody from '../model/UpdateNotificationStatusRequestBody';

/**
* Identifiers service.
* @module api/IdentifiersApi
* @version 1.0.0
*/
export default class IdentifiersApi {

    /**
    * Constructs a new IdentifiersApi. 
    * @alias module:api/IdentifiersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getIdentifierInvite operation.
     * @callback module:api/IdentifiersApi~getIdentifierInviteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetInviteResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch an invitation code and identifier auth data.
     * Retrieves the invitation data for a given invite code.
     * @param {String} invite The invitation code
     * @param {module:api/IdentifiersApi~getIdentifierInviteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetInviteResponse}
     */
    getIdentifierInvite(invite, callback) {
      let postBody = null;
      // verify the required parameter 'invite' is set
      if (invite === undefined || invite === null) {
        throw new Error("Missing the required parameter 'invite' when calling getIdentifierInvite");
      }

      let pathParams = {
        'invite': invite
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetInviteResponse;
      return this.apiClient.callApi(
        '/members/invite/{invite}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the patchNotifyStatus operation.
     * @callback module:api/IdentifiersApi~patchNotifyStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateIdentifierResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the status of a notification.
     * Updates the status of a notification identifier.
     * @param {Object} opts Optional parameters
     * @param {module:model/UpdateNotificationStatusRequestBody} [updateNotificationStatusRequestBody] 
     * @param {module:api/IdentifiersApi~patchNotifyStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateIdentifierResponse}
     */
    patchNotifyStatus(opts, callback) {
      opts = opts || {};
      let postBody = opts['updateNotificationStatusRequestBody'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateIdentifierResponse;
      return this.apiClient.callApi(
        '/members/notify/status', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postInviteStatus operation.
     * @callback module:api/IdentifiersApi~postInviteStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InviteStatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check the status of an invite.
     * Checks the status of an invitation without modifying it.
     * @param {Object} opts Optional parameters
     * @param {module:model/InviteStatusRequestBody} [inviteStatusRequestBody] 
     * @param {module:api/IdentifiersApi~postInviteStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InviteStatusResponse}
     */
    postInviteStatus(opts, callback) {
      opts = opts || {};
      let postBody = opts['inviteStatusRequestBody'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InviteStatusResponse;
      return this.apiClient.callApi(
        '/members/invite/status', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postNotifyMemberViaIdentifier operation.
     * @callback module:api/IdentifiersApi~postNotifyMemberViaIdentifierCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateIdentifierResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send a notification to a member via its identifier.
     * Sends a notification (email or SMS) to a member using their identifier for authentication.
     * @param {Object} opts Optional parameters
     * @param {module:model/NotifyMemberRequestBody} [notifyMemberRequestBody] 
     * @param {module:api/IdentifiersApi~postNotifyMemberViaIdentifierCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateIdentifierResponse}
     */
    postNotifyMemberViaIdentifier(opts, callback) {
      opts = opts || {};
      let postBody = opts['notifyMemberRequestBody'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateIdentifierResponse;
      return this.apiClient.callApi(
        '/members/notify', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postStoreAndSendIdentifierInvite operation.
     * @callback module:api/IdentifiersApi~postStoreAndSendIdentifierInviteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetInviteResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Store an invitation code and send notification.
     * Stores an invitation code and sends an invitation to the member via their identifier.
     * @param {Object} opts Optional parameters
     * @param {module:model/InviteRequestBody} [inviteRequestBody] 
     * @param {module:api/IdentifiersApi~postStoreAndSendIdentifierInviteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetInviteResponse}
     */
    postStoreAndSendIdentifierInvite(opts, callback) {
      opts = opts || {};
      let postBody = opts['inviteRequestBody'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GetInviteResponse;
      return this.apiClient.callApi(
        '/members/invite', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
