/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthErrorResponse from '../model/AuthErrorResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* MyAccount service.
* @module api/MyAccountApi
* @version 1.0.0
*/
export default class MyAccountApi {

    /**
    * Constructs a new MyAccountApi. 
    * @alias module:api/MyAccountApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getMydexIdFromMyAccountSvt operation.
     * @callback module:api/MyAccountApi~getMydexIdFromMyAccountSvtCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check if a MyAccount SVT has an associated MydexID.
     * Retrieves the MydexID associated with a MyAccount SVT.
     * @param {String} svt The MyAccount security verification token
     * @param {module:api/MyAccountApi~getMydexIdFromMyAccountSvtCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getMydexIdFromMyAccountSvt(svt, callback) {
      let postBody = null;
      // verify the required parameter 'svt' is set
      if (svt === undefined || svt === null) {
        throw new Error("Missing the required parameter 'svt' when calling getMydexIdFromMyAccountSvt");
      }

      let pathParams = {
        'svt': svt
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/members/myaccount/{svt}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
