/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthErrorResponse from '../model/AuthErrorResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* ScotAccount service.
* @module api/ScotAccountApi
* @version 1.0.0
*/
export default class ScotAccountApi {

    /**
    * Constructs a new ScotAccountApi. 
    * @alias module:api/ScotAccountApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getMydexIdFromScotAccountSub operation.
     * @callback module:api/ScotAccountApi~getMydexIdFromScotAccountSubCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check if a ScotAccount sub GUID has an associated MydexID.
     * Retrieves the MydexID associated with a ScotAccount GUID.
     * @param {String} sub The ScotAccount GUID
     * @param {module:api/ScotAccountApi~getMydexIdFromScotAccountSubCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getMydexIdFromScotAccountSub(sub, callback) {
      let postBody = null;
      // verify the required parameter 'sub' is set
      if (sub === undefined || sub === null) {
        throw new Error("Missing the required parameter 'sub' when calling getMydexIdFromScotAccountSub");
      }

      let pathParams = {
        'sub': sub
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/members/scotaccount/{sub}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
