/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiIdaasSdkJavascript);
  }
}(this, function(expect, ApiIdaasSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiIdaasSdkJavascript.IdentifierObject();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IdentifierObject', function() {
    it('should create an instance of IdentifierObject', function() {
      // uncomment below and update the code to test IdentifierObject
      //var instance = new ApiIdaasSdkJavascript.IdentifierObject();
      //expect(instance).to.be.a(ApiIdaasSdkJavascript.IdentifierObject);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiIdaasSdkJavascript.IdentifierObject();
      //expect(instance).to.be();
    });

    it('should have the property identifier (base name: "identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instance = new ApiIdaasSdkJavascript.IdentifierObject();
      //expect(instance).to.be();
    });

    it('should have the property parentUuid (base name: "parent_uuid")', function() {
      // uncomment below and update the code to test the property parentUuid
      //var instance = new ApiIdaasSdkJavascript.IdentifierObject();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ApiIdaasSdkJavascript.IdentifierObject();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new ApiIdaasSdkJavascript.IdentifierObject();
      //expect(instance).to.be();
    });

  });

}));
