/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiIdaasSdkJavascript);
  }
}(this, function(expect, ApiIdaasSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiIdaasSdkJavascript.IdentifyRequestBody();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IdentifyRequestBody', function() {
    it('should create an instance of IdentifyRequestBody', function() {
      // uncomment below and update the code to test IdentifyRequestBody
      //var instance = new ApiIdaasSdkJavascript.IdentifyRequestBody();
      //expect(instance).to.be.a(ApiIdaasSdkJavascript.IdentifyRequestBody);
    });

    it('should have the property connectionNid (base name: "connection_nid")', function() {
      // uncomment below and update the code to test the property connectionNid
      //var instance = new ApiIdaasSdkJavascript.IdentifyRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property connectionTokenHash (base name: "connection_token_hash")', function() {
      // uncomment below and update the code to test the property connectionTokenHash
      //var instance = new ApiIdaasSdkJavascript.IdentifyRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property returnTo (base name: "return_to")', function() {
      // uncomment below and update the code to test the property returnTo
      //var instance = new ApiIdaasSdkJavascript.IdentifyRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property linkingToken (base name: "linking_token")', function() {
      // uncomment below and update the code to test the property linkingToken
      //var instance = new ApiIdaasSdkJavascript.IdentifyRequestBody();
      //expect(instance).to.be();
    });

  });

}));
