/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiIdaasSdkJavascript);
  }
}(this, function(expect, ApiIdaasSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiIdaasSdkJavascript.InviteRequestBody();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InviteRequestBody', function() {
    it('should create an instance of InviteRequestBody', function() {
      // uncomment below and update the code to test InviteRequestBody
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be.a(ApiIdaasSdkJavascript.InviteRequestBody);
    });

    it('should have the property identifier (base name: "identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property appUrl (base name: "app_url")', function() {
      // uncomment below and update the code to test the property appUrl
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "client_id")', function() {
      // uncomment below and update the code to test the property clientId
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property conNid (base name: "con_nid")', function() {
      // uncomment below and update the code to test the property conNid
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property orgId (base name: "org_id")', function() {
      // uncomment below and update the code to test the property orgId
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "project_id")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property itemId (base name: "item_id")', function() {
      // uncomment below and update the code to test the property itemId
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property messageEmail (base name: "message_email")', function() {
      // uncomment below and update the code to test the property messageEmail
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property messageSms (base name: "message_sms")', function() {
      // uncomment below and update the code to test the property messageSms
      //var instance = new ApiIdaasSdkJavascript.InviteRequestBody();
      //expect(instance).to.be();
    });

  });

}));
