/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthErrorResponse from './model/AuthErrorResponse';
import AuthErrorResponseError from './model/AuthErrorResponseError';
import CreateIdentifierResponse from './model/CreateIdentifierResponse';
import ErrorResponse from './model/ErrorResponse';
import FtcIdentifyUrlResponse from './model/FtcIdentifyUrlResponse';
import FtcSetupRequestBody from './model/FtcSetupRequestBody';
import FtcUrlResponse from './model/FtcUrlResponse';
import GetIdentifiersResponse from './model/GetIdentifiersResponse';
import GetInviteResponse from './model/GetInviteResponse';
import IdentifierAuthObject from './model/IdentifierAuthObject';
import IdentifierObject from './model/IdentifierObject';
import IdentifyRequestBody from './model/IdentifyRequestBody';
import IdentifyUrlResponse from './model/IdentifyUrlResponse';
import InviteRequestBody from './model/InviteRequestBody';
import InviteStatusRequestBody from './model/InviteStatusRequestBody';
import InviteStatusResponse from './model/InviteStatusResponse';
import NotifyMemberRequestBody from './model/NotifyMemberRequestBody';
import UpdateNotificationStatusRequestBody from './model/UpdateNotificationStatusRequestBody';
import ConnectionsApi from './api/ConnectionsApi';
import IdentifiersApi from './api/IdentifiersApi';
import MyAccountApi from './api/MyAccountApi';
import ScotAccountApi from './api/ScotAccountApi';


/**
* Identity as a Service API for member authentication, identifiers, and account management..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiIdaasSdkJavascript = require('index'); // See note below*.
* var xxxSvc = new ApiIdaasSdkJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiIdaasSdkJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiIdaasSdkJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiIdaasSdkJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthErrorResponse model constructor.
     * @property {module:model/AuthErrorResponse}
     */
    AuthErrorResponse,

    /**
     * The AuthErrorResponseError model constructor.
     * @property {module:model/AuthErrorResponseError}
     */
    AuthErrorResponseError,

    /**
     * The CreateIdentifierResponse model constructor.
     * @property {module:model/CreateIdentifierResponse}
     */
    CreateIdentifierResponse,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The FtcIdentifyUrlResponse model constructor.
     * @property {module:model/FtcIdentifyUrlResponse}
     */
    FtcIdentifyUrlResponse,

    /**
     * The FtcSetupRequestBody model constructor.
     * @property {module:model/FtcSetupRequestBody}
     */
    FtcSetupRequestBody,

    /**
     * The FtcUrlResponse model constructor.
     * @property {module:model/FtcUrlResponse}
     */
    FtcUrlResponse,

    /**
     * The GetIdentifiersResponse model constructor.
     * @property {module:model/GetIdentifiersResponse}
     */
    GetIdentifiersResponse,

    /**
     * The GetInviteResponse model constructor.
     * @property {module:model/GetInviteResponse}
     */
    GetInviteResponse,

    /**
     * The IdentifierAuthObject model constructor.
     * @property {module:model/IdentifierAuthObject}
     */
    IdentifierAuthObject,

    /**
     * The IdentifierObject model constructor.
     * @property {module:model/IdentifierObject}
     */
    IdentifierObject,

    /**
     * The IdentifyRequestBody model constructor.
     * @property {module:model/IdentifyRequestBody}
     */
    IdentifyRequestBody,

    /**
     * The IdentifyUrlResponse model constructor.
     * @property {module:model/IdentifyUrlResponse}
     */
    IdentifyUrlResponse,

    /**
     * The InviteRequestBody model constructor.
     * @property {module:model/InviteRequestBody}
     */
    InviteRequestBody,

    /**
     * The InviteStatusRequestBody model constructor.
     * @property {module:model/InviteStatusRequestBody}
     */
    InviteStatusRequestBody,

    /**
     * The InviteStatusResponse model constructor.
     * @property {module:model/InviteStatusResponse}
     */
    InviteStatusResponse,

    /**
     * The NotifyMemberRequestBody model constructor.
     * @property {module:model/NotifyMemberRequestBody}
     */
    NotifyMemberRequestBody,

    /**
     * The UpdateNotificationStatusRequestBody model constructor.
     * @property {module:model/UpdateNotificationStatusRequestBody}
     */
    UpdateNotificationStatusRequestBody,

    /**
    * The ConnectionsApi service constructor.
    * @property {module:api/ConnectionsApi}
    */
    ConnectionsApi,

    /**
    * The IdentifiersApi service constructor.
    * @property {module:api/IdentifiersApi}
    */
    IdentifiersApi,

    /**
    * The MyAccountApi service constructor.
    * @property {module:api/MyAccountApi}
    */
    MyAccountApi,

    /**
    * The ScotAccountApi service constructor.
    * @property {module:api/ScotAccountApi}
    */
    ScotAccountApi
};
