/**
 * IDaaS API
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiIdaasSdkJavascript);
  }
}(this, function(expect, ApiIdaasSdkJavascript) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiIdaasSdkJavascript.IdentifiersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IdentifiersApi', function() {
    describe('getIdentifierInvite', function() {
      it('should call getIdentifierInvite successfully', function(done) {
        //uncomment below and update the code to test getIdentifierInvite
        //instance.getIdentifierInvite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchNotifyStatus', function() {
      it('should call patchNotifyStatus successfully', function(done) {
        //uncomment below and update the code to test patchNotifyStatus
        //instance.patchNotifyStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postInviteStatus', function() {
      it('should call postInviteStatus successfully', function(done) {
        //uncomment below and update the code to test postInviteStatus
        //instance.postInviteStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postNotifyMemberViaIdentifier', function() {
      it('should call postNotifyMemberViaIdentifier successfully', function(done) {
        //uncomment below and update the code to test postNotifyMemberViaIdentifier
        //instance.postNotifyMemberViaIdentifier(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postStoreAndSendIdentifierInvite', function() {
      it('should call postStoreAndSendIdentifierInvite successfully', function(done) {
        //uncomment below and update the code to test postStoreAndSendIdentifierInvite
        //instance.postStoreAndSendIdentifierInvite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
